# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 高级切图工
email: jinzhenzu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  现任职于奇虎360，前端开发工程师，玩点数据可视化。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  jzz4012650

# Build settings
markdown: kramdown
